# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 20:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formula', models.CharField(max_length=50)),
                ('quantity', models.PositiveIntegerField()),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('kind', models.CharField(choices=[('45-45', '45-45'), ('45-90', '45-90'), ('90-90', '90-90')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Opening',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OpeningKind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('dvh', models.BooleanField()),
                ('cuts', models.ManyToManyField(to='main.Cut')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('length', models.IntegerField(default=6000)),
                ('weight', models.DecimalField(decimal_places=3, max_digits=7)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('catalog', models.FileField(blank=True, null=True, upload_to='')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Brand')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.System'),
        ),
        migrations.AddField(
            model_name='openingkind',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.System'),
        ),
        migrations.AddField(
            model_name='opening',
            name='kind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.OpeningKind'),
        ),
        migrations.AddField(
            model_name='cut',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Profile'),
        ),
    ]
