# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='openingkind',
            name='name',
            field=models.CharField(default='v', max_length=50),
            preserve_default=False,
        ),
    ]
